default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  # database: lone_worker11_new_1_may_dev
  database: basic_develop
  #database: hubhuman_dev4
  username: postgres
  password: postgres

production:
  <<: *default
  database: d9fo7q9u6ktlng
  host: ec2-54-152-175-141.compute-1.amazonaws.com
  username: onauywcwfzthib
  password: 08b59eeb26d136fccc9dc6b499cb1936da51c94a570627ef39155284f0cd888e
test:
  <<: *default
  database: rorapi
  host: 182.75.88.146
  username: postgres
  password: hnjfwer8t45whbrw789234r%435
aws:
  <<: *default
  database: ebdb
  host: aa1gqeslrnjmsq7.cvd3esvflamb.us-east-1.rds.amazonaws.com
  username: postgres
  password: postgres
